Edits for the chemistry module
bmorris3/shone pull request #10
Opened 2024-05-24 00:51 UTC by nborsato

I just went through the chemistry example running the code and reading through the docs, I've made some edits to both the code and the text to try to help clarify some things.

2024-05-25 21:02 UTC, Hoeijmakers approved these changes
I think this looks good. Not sure why line 22 is needed, but it's not a big deal. Good to plot the TP profile.

2024-05-29 01:10 UTC, bmorris3 requested changes
Thanks @nborsato! Here's some feedback.

2024-05-29 01:10 UTC, bmorris3 commented on docs/shone/examples/chemistry.rst
> +    temperature = 2300 * (np.geomspace(1e-6, 10, pressure.size) / 0.1) ** 0.1  # [K]
The way I wrote it was redundant. Here's a suggestion for consistency and clarity:
```suggestion
    temperature = 2300 * (pressure / 0.1) ** 0.1  # [K]
```

2024-05-29 01:10 UTC, bmorris3 commented on docs/shone/examples/chemistry.rst
> +    temperature = 2300 * (np.geomspace(1e-6, 10, pressure.size) / 0.1) ** 0.1  # [K]
Bonus points if you make the same correction in your source code on line 38: https://github.com/bmorris3/shone/pull/10/files#diff-01b0298e1f6dacf74ab16c88d2889005257e03744cf3ada15277fcbc254a0aa6R38

2024-05-29 01:10 UTC, bmorris3 commented on docs/shone/examples/chemistry.rst
> +Radiative transfer calculations require the mixing ratios, which are the proportions of each species that exist within the atmosphere. These ratios are functions of temperature, pressure, atmospheric
```suggestion
Radiative transfer calculations require the volume mixing ratio (VMR) of each atmospheric species. The VMR is a function of temperature, pressure, atmospheric metallicity, and the carbon-to-oxygen ratio. We specify these parameters as follows:
```

2024-05-29 01:10 UTC, bmorris3 commented on docs/shone/examples/chemistry.rst
> +          <td>0.00054857990907</td>
```suggestion
          <td>0.000549</td>
```

2024-05-29 01:10 UTC, bmorris3 commented on docs/shone/examples/chemistry.rst
> +          <td>26.9815385</td>
```suggestion
          <td>26.98</td>
```

2024-05-31 17:59 UTC, bmorris3 approved these changes
Thanks @nborsato!

2024-05-31 17:59 UTC, merged